package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, March 4, 2023 10:47:23 AM CST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
