package com.cpre550.project2.restaurant.common;


/**
* com/cpre550/project2/restaurant/common/CustomerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from restaurant.idl
* Saturday, March 11, 2023 1:00:57 PM CST
*/

public interface CustomerOperations 
{
  String view_menu ();
  String place_order (String order);
  String check_order_status (String username);
} // interface CustomerOperations
