package com.cpre550.project2.restaurant.common;


/**
* com/cpre550/project2/restaurant/common/CustomerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from restaurant.idl
* Saturday, March 11, 2023 1:00:57 PM CST
*/

public abstract class CustomerPOA extends org.omg.PortableServer.Servant
 implements com.cpre550.project2.restaurant.common.CustomerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("view_menu", new java.lang.Integer (0));
    _methods.put ("place_order", new java.lang.Integer (1));
    _methods.put ("check_order_status", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // com/cpre550/project2/restaurant/common/Customer/view_menu
       {
         String $result = null;
         $result = this.view_menu ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // com/cpre550/project2/restaurant/common/Customer/place_order
       {
         String order = in.read_string ();
         String $result = null;
         $result = this.place_order (order);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // com/cpre550/project2/restaurant/common/Customer/check_order_status
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.check_order_status (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/cpre550/project2/restaurant/common/Customer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Customer _this() 
  {
    return CustomerHelper.narrow(
    super._this_object());
  }

  public Customer _this(org.omg.CORBA.ORB orb) 
  {
    return CustomerHelper.narrow(
    super._this_object(orb));
  }


} // class CustomerPOA
