package com.cpre550.project2.restaurant.common;

/**
* com/cpre550/project2/restaurant/common/CustomerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from restaurant.idl
* Saturday, March 11, 2023 1:00:57 PM CST
*/

public final class CustomerHolder implements org.omg.CORBA.portable.Streamable
{
  public com.cpre550.project2.restaurant.common.Customer value = null;

  public CustomerHolder ()
  {
  }

  public CustomerHolder (com.cpre550.project2.restaurant.common.Customer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.cpre550.project2.restaurant.common.CustomerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.cpre550.project2.restaurant.common.CustomerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.cpre550.project2.restaurant.common.CustomerHelper.type ();
  }

}
