package com.cpre550.project2.restaurant.common;


/**
* com/cpre550/project2/restaurant/common/Customer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from restaurant.idl
* Saturday, March 11, 2023 1:00:57 PM CST
*/

public interface Customer extends CustomerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Customer
