package com.cpre550.project2.restaurant.common;


/**
* com/cpre550/project2/restaurant/common/ManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from restaurant.idl
* Saturday, March 11, 2023 1:00:57 PM CST
*/

public interface ManagerOperations 
{
  String connect ();
  void keepalive (String token);
  String view_current_orders ();
} // interface ManagerOperations
