package com.cpre550.project2.test_proj;


/**
* com/cpre550/project2/test_proj/_TestInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test_app.idl
* Saturday, March 4, 2023 2:01:24 PM CST
*/

public class _TestInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements com.cpre550.project2.test_proj.TestInterface
{

  public int get_index (short index)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("get_index", true);
                $out.write_ushort (index);
                $in = _invoke ($out);
                int $result = $in.read_ulong ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return get_index (index        );
            } finally {
                _releaseReply ($in);
            }
  } // get_index

  public void set_index (short index, int val)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("set_index", true);
                $out.write_ushort (index);
                $out.write_ulong (val);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                set_index (index, val        );
            } finally {
                _releaseReply ($in);
            }
  } // set_index

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/cpre550/project2/test_proj/TestInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _TestInterfaceStub
