package com.cpre550.project2.test_proj;


/**
* com/cpre550/project2/test_proj/TestInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test_app.idl
* Saturday, March 4, 2023 2:01:24 PM CST
*/

public interface TestInterfaceOperations 
{
  int get_index (short index);
  void set_index (short index, int val);
} // interface TestInterfaceOperations
