package com.cpre550.project2.test_proj;


/**
* com/cpre550/project2/test_proj/TestInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test_app.idl
* Saturday, March 4, 2023 2:01:24 PM CST
*/

public interface TestInterface extends TestInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final short SIZE = (short)(32);
} // interface TestInterface
