/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sys_monitor.h"

bool_t
xdr_load_procs_ret (XDR *xdrs, load_procs_ret objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 3,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user_name_t (XDR *xdrs, user_name_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_USERNAMES))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user_list_t (XDR *xdrs, user_list_t *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (user_name_t), (xdrproc_t) xdr_user_name_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sysinfo_c (XDR *xdrs, sysinfo_c *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (8 + ( 3 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_long (xdrs, &objp->uptime))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->loads, 3,
				sizeof (u_long), (xdrproc_t) xdr_u_long))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->totalram))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->freeram))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->sharedram))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->bufferram))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->totalswap))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->freeswap))
				 return FALSE;
			 if (!xdr_u_short (xdrs, &objp->procs))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->uptime);
		{
			register u_long *genp;

			for (i = 0, genp = objp->loads;
				i < 3; ++i) {
				IXDR_PUT_U_LONG(buf, *genp++);
			}
		}
		IXDR_PUT_U_LONG(buf, objp->totalram);
		IXDR_PUT_U_LONG(buf, objp->freeram);
		IXDR_PUT_U_LONG(buf, objp->sharedram);
		IXDR_PUT_U_LONG(buf, objp->bufferram);
		IXDR_PUT_U_LONG(buf, objp->totalswap);
		IXDR_PUT_U_LONG(buf, objp->freeswap);
		IXDR_PUT_U_SHORT(buf, objp->procs);
		}
		 if (!xdr_vector (xdrs, (char *)objp->_f, 22,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (8 + ( 3 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_long (xdrs, &objp->uptime))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->loads, 3,
				sizeof (u_long), (xdrproc_t) xdr_u_long))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->totalram))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->freeram))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->sharedram))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->bufferram))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->totalswap))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->freeswap))
				 return FALSE;
			 if (!xdr_u_short (xdrs, &objp->procs))
				 return FALSE;

		} else {
		objp->uptime = IXDR_GET_LONG(buf);
		{
			register u_long *genp;

			for (i = 0, genp = objp->loads;
				i < 3; ++i) {
				*genp++ = IXDR_GET_U_LONG(buf);
			}
		}
		objp->totalram = IXDR_GET_U_LONG(buf);
		objp->freeram = IXDR_GET_U_LONG(buf);
		objp->sharedram = IXDR_GET_U_LONG(buf);
		objp->bufferram = IXDR_GET_U_LONG(buf);
		objp->totalswap = IXDR_GET_U_LONG(buf);
		objp->freeswap = IXDR_GET_U_LONG(buf);
		objp->procs = IXDR_GET_U_SHORT(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->_f, 22,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_long (xdrs, &objp->uptime))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->loads, 3,
		sizeof (u_long), (xdrproc_t) xdr_u_long))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->totalram))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->freeram))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->sharedram))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->bufferram))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->totalswap))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->freeswap))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->procs))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->_f, 22,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mallinfo_c (XDR *xdrs, mallinfo_c *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->arena))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ordblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->smblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->hblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->hblkhd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->usmblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fsmblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->uordblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fordblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->keepcost))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->arena);
			IXDR_PUT_LONG(buf, objp->ordblks);
			IXDR_PUT_LONG(buf, objp->smblks);
			IXDR_PUT_LONG(buf, objp->hblks);
			IXDR_PUT_LONG(buf, objp->hblkhd);
			IXDR_PUT_LONG(buf, objp->usmblks);
			IXDR_PUT_LONG(buf, objp->fsmblks);
			IXDR_PUT_LONG(buf, objp->uordblks);
			IXDR_PUT_LONG(buf, objp->fordblks);
			IXDR_PUT_LONG(buf, objp->keepcost);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->arena))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ordblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->smblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->hblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->hblkhd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->usmblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fsmblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->uordblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fordblks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->keepcost))
				 return FALSE;
		} else {
			objp->arena = IXDR_GET_LONG(buf);
			objp->ordblks = IXDR_GET_LONG(buf);
			objp->smblks = IXDR_GET_LONG(buf);
			objp->hblks = IXDR_GET_LONG(buf);
			objp->hblkhd = IXDR_GET_LONG(buf);
			objp->usmblks = IXDR_GET_LONG(buf);
			objp->fsmblks = IXDR_GET_LONG(buf);
			objp->uordblks = IXDR_GET_LONG(buf);
			objp->fordblks = IXDR_GET_LONG(buf);
			objp->keepcost = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->arena))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ordblks))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->smblks))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->hblks))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->hblkhd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->usmblks))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fsmblks))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->uordblks))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fordblks))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->keepcost))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mem_usage_ret (XDR *xdrs, mem_usage_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_mallinfo_c (xdrs, &objp->dynamic_memory_usage))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->page_size))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->phys_page_cnt))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->available_phys_page_cnt))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user_info (XDR *xdrs, user_info *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	 if (!xdr_user_list_t (xdrs, &objp->user_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dt_ops_t (XDR *xdrs, dt_ops_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_load_time_map_t (XDR *xdrs, load_time_map_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
