/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "test.h"

bool_t
xdr_set_params (XDR *xdrs, set_params *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->index))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->setval))
		 return FALSE;
	return TRUE;
}
