/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct set_params {
	u_int index;
	int setval;
};
typedef struct set_params set_params;

#define TESTPROG 0x20000001
#define TESTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define test_get 1
extern  int * test_get_1(u_int *, CLIENT *);
extern  int * test_get_1_svc(u_int *, struct svc_req *);
#define test_set 2
extern  bool_t * test_set_1(struct set_params *, CLIENT *);
extern  bool_t * test_set_1_svc(struct set_params *, struct svc_req *);
extern int testprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define test_get 1
extern  int * test_get_1();
extern  int * test_get_1_svc();
#define test_set 2
extern  bool_t * test_set_1();
extern  bool_t * test_set_1_svc();
extern int testprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_set_params (XDR *, set_params*);

#else /* K&R C */
extern bool_t xdr_set_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
